/*
 * DO NOT EDIT THIS FILE. Generated by checkmk.
 * Edit the original source file "test/unit-test.check" instead.
 */

#include <check.h>

#line 1 "test/unit-test.check"
#include <stdio.h>
#include <stdlib.h>
#include <unistd.h>
#include <fcntl.h>
#include <curl/curl.h>
#include "socket.h"
#include "irc.h"
#include "gperf.h"
#include "helper.h"
#include "bot.h"
#include "http.h"

struct irc_type {
	int sock;
	char address[SERVLEN];
	char port[PORTLEN];
	char nick[NICKLEN];
	char user[USERLEN];
	char channel[CHANLEN];
};

Irc server;
char test_buffer[BUFSIZE + 1];
int sock, status;
Parsed_data pdata;

ssize_t sock_readbyte(int sock, char *byte);
size_t curl_write_memory(char *data, size_t size, size_t elements, void *membuf);

void open_read(void) {

	server = malloc_w(sizeof(struct irc_type));
	server->sock = open("test/input.txt", O_RDONLY);
	if (server->sock < 0)
		exit_msg("Failed to open file");
}

void close_read(void) {

	free(server);
}

void open_write(void) {

	server = malloc_w(sizeof(struct irc_type));
	server->sock = open("test/output.txt", O_RDWR);
	if (server->sock < 0)
		exit_msg("Failed to open file");

	lseek(server->sock, 0, SEEK_SET);
	pdata = malloc_w(sizeof(struct parse_type));
}

void close_write(void) {

	free(pdata);
	quit_server(server, NULL);
}

/*****************************************************************************/

START_TEST(socket_connection)
{
#line 65

	sock = sock_connect("chat.freenode.net", "6667");
	ck_assert_msg(sock >= 0, "Socket creation failed");
	close(sock);

}
END_TEST

START_TEST(irc_connection)
{
#line 71

	server = connect_server(0);
	ck_assert_msg(server != NULL, "irc connection failed");
	quit_server(server, NULL);

/*****************************************************************************/

}
END_TEST
START_TEST(socket_readbytes)
{
#line 80

	char c;
	int i;

	for (i = 0; sock_readbyte(server->sock, &c) > 0; i++)
		test_buffer[i] = c;
	test_buffer[i] = '\0';

	ck_assert_str_eq("lol\r\ntroll\r\n", test_buffer);

}
END_TEST

START_TEST(socket_readline)
{
#line 91

	char test_buffer2[BUFSIZE + 1] = { 0 };

	lseek(server->sock, 0, SEEK_SET);
	while (sock_readline(server->sock, test_buffer, BUFSIZE) > 0)
		strcat(test_buffer2, test_buffer);

	ck_assert_str_eq("lol\r\ntroll\r\n", test_buffer2);

}
END_TEST

START_TEST(irc_readline)
{
#line 101

	char test_buffer2[BUFSIZE + 1] = { 0 };

	lseek(server->sock, 0, SEEK_SET);
	while (get_line(server, test_buffer) > 0)
		strcat(test_buffer2, test_buffer);

	ck_assert_str_eq("lol\r\ntroll\r\n", test_buffer2);

/*****************************************************************************/

}
END_TEST
START_TEST(write_equal_size)
{
#line 114

	ssize_t n = sock_write(server->sock, "rofl", 4);
	ck_assert_msg(n == 4 || n == -1, "Unexpected amount of bytes sent");

}
END_TEST

START_TEST(write_smaller_size)
{
#line 119

	ssize_t n = sock_write(server->sock, "troll", 0);
	ck_assert_msg(n == 0 || n == -1, "Unexpected amount of bytes sent");

}
END_TEST

START_TEST(set_nick_null)
{
#line 124

	sprintf(test_buffer, "NICK %s\r\n", server->nick);
	char *nick = set_nick(server, NULL);
	ck_assert_str_eq(test_buffer, nick);

}
END_TEST

START_TEST(new_nick_match)
{
#line 130

	char *nick = set_nick(server, "trololol");
	sprintf(test_buffer, "NICK %s\r\n", server->nick);
	ck_assert_str_eq(test_buffer, nick);

}
END_TEST

START_TEST(set_user_null)
{
#line 136

	sprintf(test_buffer, "USER %s 0 * :%s\r\n", server->user, server->user);
	char *user = set_user(server, NULL);
	ck_assert_str_eq(test_buffer, user);

}
END_TEST

START_TEST(new_user_match)
{
#line 142

	char *user = set_user(server, "trololol");
	sprintf(test_buffer, "USER %s 0 * :%s\r\n", server->user, server->user);
	ck_assert_str_eq(test_buffer, user);

}
END_TEST

START_TEST(set_chan_null)
{
#line 148

	sprintf(test_buffer, "JOIN #%s\r\n", server->channel);
	char *channel = join_channel(server, NULL);
	ck_assert_str_eq(test_buffer, channel);

}
END_TEST

START_TEST(new_chan_match)
{
#line 154

	char *channel = join_channel(server, "trololol");
	sprintf(test_buffer, "JOIN #%s\r\n", server->channel);
	ck_assert_str_eq(test_buffer, channel);

}
END_TEST

START_TEST(parse_msg)
{
#line 160

	char line[] = ":freestyl3r!~free@ppp005055033225.access.hol.gr PRIVEMSG #foss-teimes :freestylerbot";

	parse_line(server, line, pdata);
	sprintf(test_buffer, "%s%s%s", pdata->nick, pdata->command, pdata->message);
	ck_assert_str_eq(test_buffer, "freestyl3rPRIVEMSG#foss-teimes :freestylerbot");

}
END_TEST

START_TEST(sendircmsg)
{
#line 168

	char msg[] = ":freestyl3r!~free@ppp005055033225.access.hol.gr PRIVMSG #foss-teimes :freestylerbot";

	parse_line(server, msg, pdata);
	char *sent = send_message(server, pdata->target, "sup %s?", pdata->nick);
	ck_assert_str_eq(sent, "PRIVMSG #foss-teimes :sup freestyl3r?\r\n");

}
END_TEST

START_TEST(privemsg)
{
#line 176

	char msg[] = "freestyl3r\0PRIVEMSG\0freestylerbot :!bot lol re";

	pdata->nick = &msg[0];
	pdata->command = &msg[11];
	pdata->message = &msg[20];

	irc_privmsg(server, pdata);
	sprintf(test_buffer, "%s%s%s%s", pdata->nick, pdata->target, pdata->command, pdata->message);
	ck_assert_str_eq(test_buffer, "freestyl3rfreestyl3rbotlol re");

}
END_TEST

START_TEST(pingreply)
{
#line 188

	char msg[] = "PING :pratchett.freenode.net\r\n";
	char *pong = ping_reply(server, msg);
	ck_assert_str_eq(pong, "PONG :pratchett.freenode.net\r\n");

}
END_TEST

START_TEST(bot_command)
{
#line 194

	pdata->target = "room";
	pdata->nick = "troll";

	char *msg = bot(server, pdata);
	ck_assert_str_eq(msg, "PRIVMSG room :sup troll?\r\n");

/*****************************************************************************/

}
END_TEST
START_TEST(gperf)
{
#line 205

	Function_list flist = function_lookup("bot", 3);
	ck_assert_ptr_ne(flist, NULL);

	flist = function_lookup("random", 6);
	ck_assert_ptr_eq(flist, NULL);

}
END_TEST

START_TEST(curl_writeback)
{
#line 213

	struct mem_buffer mem;
	char *data = "random stuff ftw!";
	curl_write_memory(data, strlen(data), 1, &mem);
	ck_assert_str_eq(data, mem.buffer);

}
END_TEST

START_TEST(url_shortener_valid)
{
#line 220

	char *short_url = shorten_url("rofl.com");
	ck_assert_ptr_ne(short_url, NULL);

}
END_TEST

START_TEST(parameter_extraction)
{
#line 225

	char msg[] = " 	trolol  re noob  	\r\n";
	char **argv;
	int argc;

	argv = extract_params(msg, &argc);
	ck_assert_int_eq(argc, 3);
	ck_assert_str_eq(argv[0], "trolol");
	ck_assert_str_eq(argv[1], "re");
	ck_assert_str_eq(argv[2], "noob");

	free(argv);

}
END_TEST

START_TEST(mumble_list)
{
#line 239

	char *data = fetch_mumble_users();
	printf("%s\n", data);

/*****************************************************************************/

}
END_TEST

int main(void)
{
    Suite *s1 = suite_create("irc bot");
    TCase *tc1_1 = tcase_create("connection");
    TCase *tc1_2 = tcase_create("socket read operations");
    TCase *tc1_3 = tcase_create("socket write operations");
    TCase *tc1_4 = tcase_create("function match");
    SRunner *sr = srunner_create(s1);
    int nf;

    /* User-specified pre-run code */
#line 246
	tcase_add_unchecked_fixture(tc1_2, open_read, close_read);
	tcase_add_unchecked_fixture(tc1_3, open_write, close_write);
	curl_global_init(CURL_GLOBAL_ALL);


    suite_add_tcase(s1, tc1_1);
    tcase_add_test(tc1_1, socket_connection);
    tcase_add_test(tc1_1, irc_connection);
    suite_add_tcase(s1, tc1_2);
    tcase_add_test(tc1_2, socket_readbytes);
    tcase_add_test(tc1_2, socket_readline);
    tcase_add_test(tc1_2, irc_readline);
    suite_add_tcase(s1, tc1_3);
    tcase_add_test(tc1_3, write_equal_size);
    tcase_add_test(tc1_3, write_smaller_size);
    tcase_add_test(tc1_3, set_nick_null);
    tcase_add_test(tc1_3, new_nick_match);
    tcase_add_test(tc1_3, set_user_null);
    tcase_add_test(tc1_3, new_user_match);
    tcase_add_test(tc1_3, set_chan_null);
    tcase_add_test(tc1_3, new_chan_match);
    tcase_add_test(tc1_3, parse_msg);
    tcase_add_test(tc1_3, sendircmsg);
    tcase_add_test(tc1_3, privemsg);
    tcase_add_test(tc1_3, pingreply);
    tcase_add_test(tc1_3, bot_command);
    suite_add_tcase(s1, tc1_4);
    tcase_add_test(tc1_4, gperf);
    tcase_add_test(tc1_4, curl_writeback);
    tcase_add_test(tc1_4, url_shortener_valid);
    tcase_add_test(tc1_4, parameter_extraction);
    tcase_add_test(tc1_4, mumble_list);

    srunner_run_all(sr, CK_ENV);
    nf = srunner_ntests_failed(sr);
    srunner_free(sr);

    /* User-specified post-run code */
#line 251
	curl_global_cleanup();
	return nf == 0 ? 0 : 1;
}
