#ifndef GPERF_H
#define GPERF_H

/**
 * @file gperf.h
 * Static lookup table generated by gperf for high speed key -> value matching
 */

#include "irc.h"
#include "commands.h"
#include "mpd.h"

typedef void (*func_ptr)(Irc, struct parsed_data);

/** Key / value pair */
typedef const struct command_entry {
	char *name;        //!< String containing the command
	func_ptr function; //!< Function pointer to corresponding command
} Command;

/**
 * Query the lookup table
 *
 * @param str  String containing a command to search for
 * @param len  String's len
 * @returns    Pointer to the struct that matched "str" or NULL for no match.
 */
const struct command_entry *command_lookup(register const char *str, register unsigned int len);

#endif

