#ifndef GPERF_H
#define GPERF_H

#include "irc.h"
#include "bot.h"

typedef char *(*func_ptr)(Irc, Parsed_data);
typedef const struct function_list {
	char *command;
	func_ptr function;
} *Function_list;

// Introduce static lookup table, generated by gperf for high speed matching string -> functions
// Returns a pointer to the struct that matched "str". The struct's function member, points to a fuction
// that is predefinded to handle the string command action. Returns NULL for no match.
const struct function_list *function_lookup (register const char *str, register unsigned int len);

#endif